@url = http://localhost:3000
### Obtener todos los clientes
GET {{url}}/clientes
Accept: application/json

### Obtener cliente por ID
GET {{url}}/clientes/6
Accept: application/json

### Crear nuevo cliente
POST {{url}}/clientes
Content-Type: application/json

{
  "nombre": "Adriel Chad",
  "apellido": "Barrios",
  "telefono": "+123344534344",
  "email": "chadNNn@gmail.com"
}

### Actualizar cliente
PUT {{url}}/clientes/8
Content-Type: application/json

{
  "nombre": "Adriel Onechan",
  "apellido": "Barrios",
  "telefono": "+123344534344",
  "email": "chadNNn@gmail.com"
}

### Eliminar cliente
DELETE {{url}}/clientes/1